language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - hhvm

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: phpunit --testsuite servelat-unit