language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - hhvm

before_script:
  - php composer.phar install --dev --no-interaction

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --testsuite servelat-unit

after_script:
  - php vendor/bin/coveralls